version: 2.1

executors:
  ruby:
    docker:
      - image: ruby:3.0.0

  docker-in-docker:
    docker:
      - image: docker:18.06.1-ce

workflows:
  do-something:
    jobs:
      - print-something:
          name: OK
  run-tests:
    jobs:
      - test-ruby:
          name: ruby-unit-tests
      - deploy-ruby:
          name: deploy-ruby
          requires:
            - ruby-unit-tests
          filters:
            branches:
              only: master


jobs:
  print-something: 
    executor: ruby
    steps:
      - run:
          name: print hello world
          command: |
            echo "Hello World!"
            ls
  test-ruby:
    executor: ruby
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: bundler install
      - run:
          name: Run tests
          command: rspec --format documentation

  deploy-ruby:
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build . -t stevensim226/steven-ruby
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
            docker push stevensim226/steven-ruby:latest
