version: 2.1

executors:
  ruby:
    docker:
      - image: ruby:3.0.0

  docker-in-docker:
    docker:
      - image: docker:18.06.1-ce

workflows:
  run-tests:
    jobs:
      - test-ruby:
          name: ruby-unit-tests
      - deploy-ruby:
          name: deploy-ruby
          requires:
            - ruby-unit-tests


jobs:
  test-ruby:
    executor: ruby
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: bundler install
      - run:
          name: Run tests
          command: rspec --format documentation

  deploy-ruby:
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build . -t steven-ruby
            docker run -d -p 8000:3000 steven-ruby
            curl localhost:8000/cars/homepage
