version: 2.1

executors:
  ruby:
    docker:
      - image: ruby:3.0.0

workflows:
  run-tests:
    jobs:
      - test-ruby:
          name: ruby-unit-tests
      - deploy-ruby:
          name: deploy-ruby
          requires:
            - ruby-unit-tests


jobs:
  test-ruby:
    executor: ruby
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: bundler install
      - run:
          name: Run tests
          command: rspec

  deploy-ruby:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Deploy (supposed)
          command: |
            echo "Hello World!!!"